version: "3.9"

services:
  video_merge_bot:
    image: python:3.10-slim
    container_name: video-merge-bot
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_OWNER=${BOT_OWNER}
      - SESSION_NAME=${SESSION_NAME}
      - UPDATES_CHANNEL=${UPDATES_CHANNEL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DOWN_PATH=${DOWN_PATH}
      - MAX_VIDEOS=${MAX_VIDEOS}
      - IMG_FOLDER=${IMG_FOLDER}
      - STREAMTAPE_API_USERNAME=${STREAMTAPE_API_USERNAME}
      - STREAMTAPE_API_PASS=${STREAMTAPE_API_PASS}
      - MONGODB_URI=${MONGODB_URI}
      - TIME_GAP=${TIME_GAP}
      - BROADCAST_AS_COPY=${BROADCAST_AS_COPY}
    command: python3 -m bot
    ports:
      - "8080:8080" 
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
